[tools]
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
"github:usagi-flow/evil-helix" = "latest"
lazygit = "latest"
rg = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
experimental = true
ignored_config_paths = [ "/home/mhzen/.local/share/chezmoi" ]
